# docker stack deploy -c docker-compose.yml bindman-dns-manager
version: '3.5'

services:

  bind:
    image: abilioesteves/bind9:0.0.3
    volumes:
      - data:/keys
    ports:
    - "53:53/udp"
    - "53:53/tcp"
    - "10000:10000/tcp"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 5s

  bindman-dns-bind9:
    image: labbsr0x/bindman-dns-bind9
    build: .
    volumes:
      - data:/data
    ports:
      - 7070:7070
    environment:
      - BINDMAN_NAMESERVER_ADDRESS=bind
      - BINDMAN_NAMESERVER_KEY_FILE=K.ir.+157+50086.key
      - BINDMAN_NAMESERVER_ZONE=.ir
      - BINDMAN_DNS_REMOVAL_DELAY=1
      - BINDMAN_DEBUG=false

volumes:
  data:
